M48
; DRILL file {KiCad 7.0.8} date 2023 November 07, Tuesday 21:40:32
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-07T21:40:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.8215Y-2.2273
X4.8215Y-4.1564
X7.105Y-2.2273
X7.105Y-4.1564
T0
M30
